// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: condition/v1/condition.proto

package conditionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConditionProvider_Evaluate_FullMethodName = "/condition.v1.ConditionProvider/Evaluate"
)

// ConditionProviderClient is the client API for ConditionProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConditionProvider — спільний контракт усіх provider-сервісів
// (cosmos / chronos / chaos). Орхестратор викликає Evaluate у кожного.
type ConditionProviderClient interface {
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
}

type conditionProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewConditionProviderClient(cc grpc.ClientConnInterface) ConditionProviderClient {
	return &conditionProviderClient{cc}
}

func (c *conditionProviderClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, ConditionProvider_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConditionProviderServer is the server API for ConditionProvider service.
// All implementations must embed UnimplementedConditionProviderServer
// for forward compatibility.
//
// ConditionProvider — спільний контракт усіх provider-сервісів
// (cosmos / chronos / chaos). Орхестратор викликає Evaluate у кожного.
type ConditionProviderServer interface {
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	mustEmbedUnimplementedConditionProviderServer()
}

// UnimplementedConditionProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConditionProviderServer struct{}

func (UnimplementedConditionProviderServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedConditionProviderServer) mustEmbedUnimplementedConditionProviderServer() {}
func (UnimplementedConditionProviderServer) testEmbeddedByValue()                           {}

// UnsafeConditionProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConditionProviderServer will
// result in compilation errors.
type UnsafeConditionProviderServer interface {
	mustEmbedUnimplementedConditionProviderServer()
}

func RegisterConditionProviderServer(s grpc.ServiceRegistrar, srv ConditionProviderServer) {
	// If the following call panics, it indicates UnimplementedConditionProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConditionProvider_ServiceDesc, srv)
}

func _ConditionProvider_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConditionProviderServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConditionProvider_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConditionProviderServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConditionProvider_ServiceDesc is the grpc.ServiceDesc for ConditionProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConditionProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "condition.v1.ConditionProvider",
	HandlerType: (*ConditionProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _ConditionProvider_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "condition/v1/condition.proto",
}
