// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: condition/v1/condition.proto

package conditionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Verdict — як умова впливає на рішення вийти на перекур.
type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED Verdict = 0
	Verdict_VERDICT_FAVORABLE   Verdict = 1 // сприяє
	Verdict_VERDICT_UNFAVORABLE Verdict = 2 // проти
	Verdict_VERDICT_NEUTRAL     Verdict = 3 // нейтрально/просто цікаво
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_FAVORABLE",
		2: "VERDICT_UNFAVORABLE",
		3: "VERDICT_NEUTRAL",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"VERDICT_FAVORABLE":   1,
		"VERDICT_UNFAVORABLE": 2,
		"VERDICT_NEUTRAL":     3,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_condition_v1_condition_proto_enumTypes[0].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_condition_v1_condition_proto_enumTypes[0]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_condition_v1_condition_proto_rawDescGZIP(), []int{0}
}

// Location — value object: координати місця, для якого оцінюємо умови.
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // людська назва ("Київ")
	Tz            string                 `protobuf:"bytes,4,opt,name=tz,proto3" json:"tz,omitempty"`     // IANA TZ ("Europe/Kyiv")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_condition_v1_condition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_condition_v1_condition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_condition_v1_condition_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetTz() string {
	if x != nil {
		return x.Tz
	}
	return ""
}

// Condition — одна оцінена умова (value object).
type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`         // машинний код, напр. "uv_index"
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // людська категорія, напр. "Природа та космос"
	Verdict       Verdict                `protobuf:"varint,3,opt,name=verdict,proto3,enum=condition.v1.Verdict" json:"verdict,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`      // вага у підсумку, напр. -3..+3
	Headline      string                 `protobuf:"bytes,5,opt,name=headline,proto3" json:"headline,omitempty"` // смішне пояснення українською
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_condition_v1_condition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_condition_v1_condition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_condition_v1_condition_proto_rawDescGZIP(), []int{1}
}

func (x *Condition) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Condition) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Condition) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *Condition) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Condition) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	UnixTs        int64                  `protobuf:"varint,2,opt,name=unix_ts,json=unixTs,proto3" json:"unix_ts,omitempty"` // момент оцінки (Unix seconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_condition_v1_condition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_condition_v1_condition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_condition_v1_condition_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *EvaluateRequest) GetUnixTs() int64 {
	if x != nil {
		return x.UnixTs
	}
	return 0
}

type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*Condition           `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_condition_v1_condition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_condition_v1_condition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_condition_v1_condition_proto_rawDescGZIP(), []int{3}
}

func (x *EvaluateResponse) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

var File_condition_v1_condition_proto protoreflect.FileDescriptor

const file_condition_v1_condition_proto_rawDesc = "" +
	"\n" +
	"\x1ccondition/v1/condition.proto\x12\fcondition.v1\"R\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x0e\n" +
	"\x02tz\x18\x04 \x01(\tR\x02tz\"\x9e\x01\n" +
	"\tCondition\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12/\n" +
	"\averdict\x18\x03 \x01(\x0e2\x15.condition.v1.VerdictR\averdict\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x1a\n" +
	"\bheadline\x18\x05 \x01(\tR\bheadline\"^\n" +
	"\x0fEvaluateRequest\x122\n" +
	"\blocation\x18\x01 \x01(\v2\x16.condition.v1.LocationR\blocation\x12\x17\n" +
	"\aunix_ts\x18\x02 \x01(\x03R\x06unixTs\"K\n" +
	"\x10EvaluateResponse\x127\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x17.condition.v1.ConditionR\n" +
	"conditions*g\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VERDICT_FAVORABLE\x10\x01\x12\x17\n" +
	"\x13VERDICT_UNFAVORABLE\x10\x02\x12\x13\n" +
	"\x0fVERDICT_NEUTRAL\x10\x032^\n" +
	"\x11ConditionProvider\x12I\n" +
	"\bEvaluate\x12\x1d.condition.v1.EvaluateRequest\x1a\x1e.condition.v1.EvaluateResponseB+Z)smoker/pkg/proto/condition/v1;conditionv1b\x06proto3"

var (
	file_condition_v1_condition_proto_rawDescOnce sync.Once
	file_condition_v1_condition_proto_rawDescData []byte
)

func file_condition_v1_condition_proto_rawDescGZIP() []byte {
	file_condition_v1_condition_proto_rawDescOnce.Do(func() {
		file_condition_v1_condition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_condition_v1_condition_proto_rawDesc), len(file_condition_v1_condition_proto_rawDesc)))
	})
	return file_condition_v1_condition_proto_rawDescData
}

var file_condition_v1_condition_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_condition_v1_condition_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_condition_v1_condition_proto_goTypes = []any{
	(Verdict)(0),             // 0: condition.v1.Verdict
	(*Location)(nil),         // 1: condition.v1.Location
	(*Condition)(nil),        // 2: condition.v1.Condition
	(*EvaluateRequest)(nil),  // 3: condition.v1.EvaluateRequest
	(*EvaluateResponse)(nil), // 4: condition.v1.EvaluateResponse
}
var file_condition_v1_condition_proto_depIdxs = []int32{
	0, // 0: condition.v1.Condition.verdict:type_name -> condition.v1.Verdict
	1, // 1: condition.v1.EvaluateRequest.location:type_name -> condition.v1.Location
	2, // 2: condition.v1.EvaluateResponse.conditions:type_name -> condition.v1.Condition
	3, // 3: condition.v1.ConditionProvider.Evaluate:input_type -> condition.v1.EvaluateRequest
	4, // 4: condition.v1.ConditionProvider.Evaluate:output_type -> condition.v1.EvaluateResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_condition_v1_condition_proto_init() }
func file_condition_v1_condition_proto_init() {
	if File_condition_v1_condition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_condition_v1_condition_proto_rawDesc), len(file_condition_v1_condition_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_condition_v1_condition_proto_goTypes,
		DependencyIndexes: file_condition_v1_condition_proto_depIdxs,
		EnumInfos:         file_condition_v1_condition_proto_enumTypes,
		MessageInfos:      file_condition_v1_condition_proto_msgTypes,
	}.Build()
	File_condition_v1_condition_proto = out.File
	file_condition_v1_condition_proto_goTypes = nil
	file_condition_v1_condition_proto_depIdxs = nil
}
