// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: advisor/v1/advisor.proto

package advisorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmokeAdvisor_Recommend_FullMethodName = "/advisor.v1.SmokeAdvisor/Recommend"
)

// SmokeAdvisorClient is the client API for SmokeAdvisor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SmokeAdvisor — core domain: агрегує умови провайдерів і видає вердикт.
type SmokeAdvisorClient interface {
	Recommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error)
}

type smokeAdvisorClient struct {
	cc grpc.ClientConnInterface
}

func NewSmokeAdvisorClient(cc grpc.ClientConnInterface) SmokeAdvisorClient {
	return &smokeAdvisorClient{cc}
}

func (c *smokeAdvisorClient) Recommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendResponse)
	err := c.cc.Invoke(ctx, SmokeAdvisor_Recommend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmokeAdvisorServer is the server API for SmokeAdvisor service.
// All implementations must embed UnimplementedSmokeAdvisorServer
// for forward compatibility.
//
// SmokeAdvisor — core domain: агрегує умови провайдерів і видає вердикт.
type SmokeAdvisorServer interface {
	Recommend(context.Context, *RecommendRequest) (*RecommendResponse, error)
	mustEmbedUnimplementedSmokeAdvisorServer()
}

// UnimplementedSmokeAdvisorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmokeAdvisorServer struct{}

func (UnimplementedSmokeAdvisorServer) Recommend(context.Context, *RecommendRequest) (*RecommendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recommend not implemented")
}
func (UnimplementedSmokeAdvisorServer) mustEmbedUnimplementedSmokeAdvisorServer() {}
func (UnimplementedSmokeAdvisorServer) testEmbeddedByValue()                      {}

// UnsafeSmokeAdvisorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmokeAdvisorServer will
// result in compilation errors.
type UnsafeSmokeAdvisorServer interface {
	mustEmbedUnimplementedSmokeAdvisorServer()
}

func RegisterSmokeAdvisorServer(s grpc.ServiceRegistrar, srv SmokeAdvisorServer) {
	// If the following call panics, it indicates UnimplementedSmokeAdvisorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmokeAdvisor_ServiceDesc, srv)
}

func _SmokeAdvisor_Recommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmokeAdvisorServer).Recommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmokeAdvisor_Recommend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmokeAdvisorServer).Recommend(ctx, req.(*RecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmokeAdvisor_ServiceDesc is the grpc.ServiceDesc for SmokeAdvisor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmokeAdvisor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "advisor.v1.SmokeAdvisor",
	HandlerType: (*SmokeAdvisorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recommend",
			Handler:    _SmokeAdvisor_Recommend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "advisor/v1/advisor.proto",
}
