// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: advisor/v1/advisor.proto

package advisorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	v1 "smoker/pkg/proto/condition/v1"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Decision — підсумкове рішення SmokeAdvisor.
type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_DECISION_GO          Decision = 1 // час на перекур
	Decision_DECISION_WAIT        Decision = 2 // краще перечекати
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_GO",
		2: "DECISION_WAIT",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"DECISION_GO":          1,
		"DECISION_WAIT":        2,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_advisor_v1_advisor_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_advisor_v1_advisor_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_advisor_v1_advisor_proto_rawDescGZIP(), []int{0}
}

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *v1.Location           `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	UnixTs        int64                  `protobuf:"varint,2,opt,name=unix_ts,json=unixTs,proto3" json:"unix_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_advisor_v1_advisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advisor_v1_advisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_advisor_v1_advisor_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendRequest) GetLocation() *v1.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *RecommendRequest) GetUnixTs() int64 {
	if x != nil {
		return x.UnixTs
	}
	return 0
}

type RecommendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      Decision               `protobuf:"varint,1,opt,name=decision,proto3,enum=advisor.v1.Decision" json:"decision,omitempty"`
	TotalScore    int32                  `protobuf:"varint,2,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	Confidence    string                 `protobuf:"bytes,3,opt,name=confidence,proto3" json:"confidence,omitempty"` // людський опис впевненості
	Reasons       []*v1.Condition        `protobuf:"bytes,4,rep,name=reasons,proto3" json:"reasons,omitempty"`       // топ причин для тексту
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`       // готовий до відправки текст (Markdown, UA)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_advisor_v1_advisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advisor_v1_advisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_advisor_v1_advisor_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *RecommendResponse) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *RecommendResponse) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *RecommendResponse) GetReasons() []*v1.Condition {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *RecommendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_advisor_v1_advisor_proto protoreflect.FileDescriptor

const file_advisor_v1_advisor_proto_rawDesc = "" +
	"\n" +
	"\x18advisor/v1/advisor.proto\x12\n" +
	"advisor.v1\x1a\x1ccondition/v1/condition.proto\"_\n" +
	"\x10RecommendRequest\x122\n" +
	"\blocation\x18\x01 \x01(\v2\x16.condition.v1.LocationR\blocation\x12\x17\n" +
	"\aunix_ts\x18\x02 \x01(\x03R\x06unixTs\"\xd3\x01\n" +
	"\x11RecommendResponse\x120\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x14.advisor.v1.DecisionR\bdecision\x12\x1f\n" +
	"\vtotal_score\x18\x02 \x01(\x05R\n" +
	"totalScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\tR\n" +
	"confidence\x121\n" +
	"\areasons\x18\x04 \x03(\v2\x17.condition.v1.ConditionR\areasons\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage*H\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDECISION_GO\x10\x01\x12\x11\n" +
	"\rDECISION_WAIT\x10\x022X\n" +
	"\fSmokeAdvisor\x12H\n" +
	"\tRecommend\x12\x1c.advisor.v1.RecommendRequest\x1a\x1d.advisor.v1.RecommendResponseB'Z%smoker/pkg/proto/advisor/v1;advisorv1b\x06proto3"

var (
	file_advisor_v1_advisor_proto_rawDescOnce sync.Once
	file_advisor_v1_advisor_proto_rawDescData []byte
)

func file_advisor_v1_advisor_proto_rawDescGZIP() []byte {
	file_advisor_v1_advisor_proto_rawDescOnce.Do(func() {
		file_advisor_v1_advisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_advisor_v1_advisor_proto_rawDesc), len(file_advisor_v1_advisor_proto_rawDesc)))
	})
	return file_advisor_v1_advisor_proto_rawDescData
}

var file_advisor_v1_advisor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_advisor_v1_advisor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_advisor_v1_advisor_proto_goTypes = []any{
	(Decision)(0),             // 0: advisor.v1.Decision
	(*RecommendRequest)(nil),  // 1: advisor.v1.RecommendRequest
	(*RecommendResponse)(nil), // 2: advisor.v1.RecommendResponse
	(*v1.Location)(nil),       // 3: condition.v1.Location
	(*v1.Condition)(nil),      // 4: condition.v1.Condition
}
var file_advisor_v1_advisor_proto_depIdxs = []int32{
	3, // 0: advisor.v1.RecommendRequest.location:type_name -> condition.v1.Location
	0, // 1: advisor.v1.RecommendResponse.decision:type_name -> advisor.v1.Decision
	4, // 2: advisor.v1.RecommendResponse.reasons:type_name -> condition.v1.Condition
	1, // 3: advisor.v1.SmokeAdvisor.Recommend:input_type -> advisor.v1.RecommendRequest
	2, // 4: advisor.v1.SmokeAdvisor.Recommend:output_type -> advisor.v1.RecommendResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_advisor_v1_advisor_proto_init() }
func file_advisor_v1_advisor_proto_init() {
	if File_advisor_v1_advisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_advisor_v1_advisor_proto_rawDesc), len(file_advisor_v1_advisor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_advisor_v1_advisor_proto_goTypes,
		DependencyIndexes: file_advisor_v1_advisor_proto_depIdxs,
		EnumInfos:         file_advisor_v1_advisor_proto_enumTypes,
		MessageInfos:      file_advisor_v1_advisor_proto_msgTypes,
	}.Build()
	File_advisor_v1_advisor_proto = out.File
	file_advisor_v1_advisor_proto_goTypes = nil
	file_advisor_v1_advisor_proto_depIdxs = nil
}
